apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: es-pvc
    namespace: es
  local:
    path: /media/kubernetes/local-storage/es-data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sicho-worker-01
